apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 5
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo
          args:
            - "-text=echo"
          ports:
            - containerPort: 5678
          env:
            - name: BUILD_NUMBER
              value: "{{ build.number }}"
