#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg SOURCE_COMMIT=$SOURCE_COMMIT -t $IMAGE_NAME .
echo "------ HOOK END - BUILD -------"